spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: *********.apps.googleusercontent.com
            clientSecret: *************



server:
  port: 8080
