spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 562102429669-2bjibkifmp2vhuig3hkppnmcqpvv58er.apps.googleusercontent.com
            clientSecret: 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



server:
  port: 8080